### ISSUE TITLE
Plan for a new stable release with bugfixes?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/languageicons#2]
Hi @alanmels,

although there's no related info in this module's readme file, I'm assuming that you are maintainer for languageicons.

Some bugs got reported in in the forum: https://forum.backdropcms.org/forum/language-icons-module-2-problems

One of these got fixed in May this year, but never released. Any chance that you find the time for a new release?

**Comment by alanmels** [comment]
@indigoxela, I'm so sorry I kept this so long, but I'm afraid I won't be able to actively participate in anything Backdrop soon. I hope you don't mind me adding you as an admin to this module. Could you please make all necessary changes - including adding yourself into README - and push a new release?

**Comment by indigoxela** [comment]
> I'm afraid I won't be able to actively participate in anything Backdrop soon

Oh, that's sad to hear.

> Could you please make all necessary changes

That's not optimal, because personally I never use language icons, and maintaining a module I never use anyway, doesn't make much sense. I just cross-linked the forum post I saw.

Maybe the @backdrop-contrib/bug-squad team can help out here?

**Comment by alanmels** [comment]
Ok, I've just rolled out a new version 1-x.1.1 and that should take care of the English flag issue. Please download it from https://github.com/backdrop-contrib/languageicons/releases/tag/1.x-1.1
