### ISSUE TITLE
greek icon

### ISSUE THREAD

**Issue by ecowebdesign** [backdrop-contrib/languageicons#3]
filename for Greece flag should be el.png , not gr.png

**Comment by alanmels** [comment]
@ecowebdesign, the filenames on [GitHub](https://github.com/backdrop-contrib/languageicons/tree/1.x-1.x/flags), which were inherited from the Drupal version, should remain unchanged. These names follow international standards, such as [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:GR) codes, and are essential for compatibility. The module relies on country codes used by various language/translation modules and visually represents them with .png files. Changing these codes in this module would require modifying the country codes across Drupal, Backdrop core, and other major modules. Language Icons is primarily a helper module, so maintaining consistency is critical.
